sudo: required

jobs:
  include:
    - stage: Test
      language: ruby
      cache:
        bundler: true
        directories:
          - /home/travis/.rvm/
      services:
        - postgresql
      env:
        - RACK_ENV=test
        - RAILS_ENV=test
        - TEST_DATABASE_URL=postgresql://postgres:@localhost/eoshub_test
      before_script:
        - psql -c 'create database eoshub_test;' -U postgres
        - bundle exec rake db:migrate
        - bundle exec rake assets:precompile
      script:
        - bundle exec rake test
    - stage: Build and Push docker image
      if: type != pull_request
      language: bash
      services:
        - docker
      script:
        - if [ -z "$TRAVIS_TAG" ]; then
            export DOCKER_TAG=$TRAVIS_COMMIT;
          else
            export DOCKER_TAG=$TRAVIS_TAG;
          fi
        - docker build -f deploy/alpha/dockerfile -t eosys/eoshub.io:$DOCKER_TAG --build-arg RAILS_MASTER_KEY=$RAILS_MASTER_KEY .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push eosys/eoshub.io:$DOCKER_TAG

notifications:
  slack:
    secure: NYIhR65QVav3UgtYE7S0hBtDpOj0V0/jZPdcab6OawphCIVAuGbDFN3whKIRDZD/Gtgcs9GBS5jKqg57GOu8uGwfv5QK3z1TrZTkJ285KMlfsreEFluDLeJBYogCwURUBsaMbZ7z4eb33qyMAH1/SCVw/R5ppxLpcSoOjlSRAwKZDyEeOHdXcRe9Jn0nOGTQEZYYT0wO3fDViu0D2mLd6ELjZONjqvkDx6w91/ZoXFg+Orpaq4IOdIHaseRS3iHihtIaNFtqJ5tzzlNx602XpWC06bsAN6Gm6brN2rVl1M6HqALYz3zwS5lqVhPdhOYNxRxdd7D+tYVzaXIqYvBf51ZOmaozLG2xrAbRMSg4kBtKB5mvWh24AUoe3+/f7PPijdu9RQOaYBY8q1HePmIgkMA3vdovbdTOv5qhEpgsHDM1bbJhAQJU574BD7APkCgHaRv5VY8qKAMZkxYNIi9EOAkxWwSfwaRCl3o8dJHnAljkaFdoOHDfn86n/uaJjlmYE6eXNu3d8LNABLxcLQsj+Bx2qNKAf2mgPL5B/P0mPIRwhKvxJQkK9h+MBnQxmGf8HfT9P3O2xtV4rvPdK0pgQvbPTalvD5SIqaJ9yNEjT51DDzGihnREZOCHicdQTX5qrf8yeo5aBDAC7M2MA+nvVioH9NKRw5+kceNIYmzL1Jo=
