default: &default
  host_url: http://localhost:3000
  eos_wallet_node_host: http://localhost:5000
  eos_account_url: /account
  account_create_email_confirmed_url: /account/email_confirmed
  account_create_email_confirm_failure_url: /account/email_confirm_failure
  eos_rpc_urls:
    - https://rpc.eosys.io
    - https://api.eosnewyork.io  # Thanks eos newyork!
    - http://mainnet.eoscalgary.io  # Thanks eos calgary!

development:
  <<: *default

test:
  <<: *default

alpha:
  <<: *default
  host_url: http://ecs-first-run-alb-1125793223.ap-northeast-2.elb.amazonaws.com
  eos_wallet_node_host: http://ecs-first-run-alb-1125793223.ap-northeast-2.elb.amazonaws.com:5000

production:
  <<: *default