default: &default
  # EOS account
  eos_account_url: /account
  
  # EOS api
  eos_rpc_urls:
    - https://rpc.eosys.io
    - https://api.eosnewyork.io  # Thanks eos newyork!
    - http://mainnet.eoscalgary.io  # Thanks eos calgary!
  eos_get_table_url: /v1/chain/get_table_rows

  # Payment
  payletter_pay_api_url: /v1.0/payments/request

development:
  <<: *default

test:
  <<: *default

alpha:
  <<: *default

production:
  <<: *default
