default: &default
  eos_wallet_node_host: localhost:5000
  eos_account_url: /account

development:
  <<: *default

test:
  <<: *default
  eos_wallet_node_host: http://ecs-first-run-alb-1125793223.ap-northeast-2.elb.amazonaws.com:5000

alpha:
  <<: *default
  eos_wallet_node_host: http://ecs-first-run-alb-1125793223.ap-northeast-2.elb.amazonaws.com:5000

production:
  <<: *default